/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as _mainLayoutRouteImport } from './routes/__mainLayout'
import { Route as _mainLayoutIndexRouteImport } from './routes/__mainLayout/index'
import { Route as _mainLayoutSettingRouteImport } from './routes/__mainLayout/setting'
import { Route as _mainLayoutHomeRouteImport } from './routes/__mainLayout/home'
import { Route as _mainLayoutContactRouteImport } from './routes/__mainLayout/contact'
import { Route as _mainLayoutAboutRouteImport } from './routes/__mainLayout/about'

const _mainLayoutRoute = _mainLayoutRouteImport.update({
  id: '/__mainLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const _mainLayoutIndexRoute = _mainLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => _mainLayoutRoute,
} as any)
const _mainLayoutSettingRoute = _mainLayoutSettingRouteImport.update({
  id: '/setting',
  path: '/setting',
  getParentRoute: () => _mainLayoutRoute,
} as any)
const _mainLayoutHomeRoute = _mainLayoutHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => _mainLayoutRoute,
} as any)
const _mainLayoutContactRoute = _mainLayoutContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => _mainLayoutRoute,
} as any)
const _mainLayoutAboutRoute = _mainLayoutAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => _mainLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof _mainLayoutIndexRoute
  '/about': typeof _mainLayoutAboutRoute
  '/contact': typeof _mainLayoutContactRoute
  '/home': typeof _mainLayoutHomeRoute
  '/setting': typeof _mainLayoutSettingRoute
}
export interface FileRoutesByTo {
  '/about': typeof _mainLayoutAboutRoute
  '/contact': typeof _mainLayoutContactRoute
  '/home': typeof _mainLayoutHomeRoute
  '/setting': typeof _mainLayoutSettingRoute
  '/': typeof _mainLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/__mainLayout': typeof _mainLayoutRouteWithChildren
  '/__mainLayout/about': typeof _mainLayoutAboutRoute
  '/__mainLayout/contact': typeof _mainLayoutContactRoute
  '/__mainLayout/home': typeof _mainLayoutHomeRoute
  '/__mainLayout/setting': typeof _mainLayoutSettingRoute
  '/__mainLayout/': typeof _mainLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/contact' | '/home' | '/setting'
  fileRoutesByTo: FileRoutesByTo
  to: '/about' | '/contact' | '/home' | '/setting' | '/'
  id:
    | '__root__'
    | '/__mainLayout'
    | '/__mainLayout/about'
    | '/__mainLayout/contact'
    | '/__mainLayout/home'
    | '/__mainLayout/setting'
    | '/__mainLayout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  _mainLayoutRoute: typeof _mainLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/__mainLayout': {
      id: '/__mainLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof _mainLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__mainLayout/': {
      id: '/__mainLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof _mainLayoutIndexRouteImport
      parentRoute: typeof _mainLayoutRoute
    }
    '/__mainLayout/setting': {
      id: '/__mainLayout/setting'
      path: '/setting'
      fullPath: '/setting'
      preLoaderRoute: typeof _mainLayoutSettingRouteImport
      parentRoute: typeof _mainLayoutRoute
    }
    '/__mainLayout/home': {
      id: '/__mainLayout/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof _mainLayoutHomeRouteImport
      parentRoute: typeof _mainLayoutRoute
    }
    '/__mainLayout/contact': {
      id: '/__mainLayout/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof _mainLayoutContactRouteImport
      parentRoute: typeof _mainLayoutRoute
    }
    '/__mainLayout/about': {
      id: '/__mainLayout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof _mainLayoutAboutRouteImport
      parentRoute: typeof _mainLayoutRoute
    }
  }
}

interface _mainLayoutRouteChildren {
  _mainLayoutAboutRoute: typeof _mainLayoutAboutRoute
  _mainLayoutContactRoute: typeof _mainLayoutContactRoute
  _mainLayoutHomeRoute: typeof _mainLayoutHomeRoute
  _mainLayoutSettingRoute: typeof _mainLayoutSettingRoute
  _mainLayoutIndexRoute: typeof _mainLayoutIndexRoute
}

const _mainLayoutRouteChildren: _mainLayoutRouteChildren = {
  _mainLayoutAboutRoute: _mainLayoutAboutRoute,
  _mainLayoutContactRoute: _mainLayoutContactRoute,
  _mainLayoutHomeRoute: _mainLayoutHomeRoute,
  _mainLayoutSettingRoute: _mainLayoutSettingRoute,
  _mainLayoutIndexRoute: _mainLayoutIndexRoute,
}

const _mainLayoutRouteWithChildren = _mainLayoutRoute._addFileChildren(
  _mainLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  _mainLayoutRoute: _mainLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
